apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-agent-principal.redisProxyServiceName" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-proxy
  {{- with .Values.service.redisProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: redis-proxy
    protocol: TCP
    port: {{ .Values.service.redisProxy.port }}
    targetPort: {{ .Values.service.redisProxy.targetPort }}
  selector:
    {{- include "argocd-agent-principal.selectorLabels" . | nindent 4 }}
