{{- if .Values.userpassSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-agent-principal.userpassSecretName" . }}
  namespace: {{ include "argocd-agent-principal.namespace" . }}
  labels:
    {{- include "argocd-agent-principal.labels" . | nindent 4 }}
stringData:
  passwd: {{ .Values.userpassSecret.passwd | quote }}
{{- end }}
